### PR TITLE
Log date to Carbon instance for change timezone (used the ```config('…

### PR DESCRIPTION
**Pull request by arturmamedov**
Used the default ```config('app.timezone')``` and the defautl formats ```Y-m-d H:i:s P``` for view.

### CODE REVIEW

**Comment by arturmamedov** [comment]
Its be very nice if we create a config file, and configuring the timezone and format inside it.

**Comment by rap2hpoutre** [comment]
Ok thank you! Could you explain a why? I'm not sure it will be a benefits for everyone, so I need to understand first.

**Comment by rap2hpoutre** [comment]
> Its be very nice if we create a config file, and configuring the timezone and format inside it.

I want to keep this package lightweight and as simple as possible (no config, 20 lines max readme and not too much code), so I don't think we will add config options.

**Comment by arturmamedov** [comment]
Yes you right! In my case i wont to see the log datetime in locale format and timezone. But for many developer this thing can be a over do. (P.S. if someone need to show logs to end user to(customer), for complete control over web application, i think its better, convert to the local timezone and format)

**Pull request closed without merging**
