### PR TITLE
Laravel 7 support

### PR DESCRIPTION
**Pull request by dtvmedia**

### CODE REVIEW

**Comment by serderovsh** [comment]
++

**Comment by rap2hpoutre** [comment]
Thank you @dtvmedia !!

**Comment by rap2hpoutre** [comment]
@mattlibera @martijnderidder @dtvmedia @ilvalerione @aglipanci @serderovsh @cornedb 

Available in v1.4.0 (thanks to @dtvmedia 🎉). Thank you for your patience!

**Comment by mattlibera** [comment]
Thanks @dtvmedia for the PR and @rap2hpoutre for the merge!

**Pull request merged**
