### PR TITLE
Multiple log view locations 162

### PR DESCRIPTION
**Pull request by elminson**
@rap2hpoutre Please check this PR address all comments from PR #169

### CODE REVIEW

**Comment by rap2hpoutre** [comment]
It looks good (just read it quickly though) but it seems it's again mixed with other code (the unit test one). Could you send a PR with only the relevant part? (I know that you are putting many effort in your work, so thank you!). Or if you prefer, I can create a PR myself to fix it and discuss with you...

**Comment by rap2hpoutre** [comment]
_Side note: I just have seen this PR https://github.com/rap2hpoutre/laravel-log-viewer/pull/145 which seems to have the same goal as yours... Did you see it? What do you think of the implementation suggested?_

**Comment by elminson** [comment]
You can Fix the PR and we can discuss about it :)

**Comment by elminson** [comment]
> _Side note: I just have seen this PR #145 which seems to have the same goal as yours... Did you see it? What do you think of the implementation suggested?_

Not sure about this PR, is from June and we already have some changes on master, you can take a look over the code and let me know if you like the #145 more than this, we can talk about. No problem. I will try to fix your comments this week (if you don't do it before hahahha lol )

**Pull request closed without merging**
