### PR TITLE
Design proposal changes

### PR DESCRIPTION
**Pull request by ahuggins**

### CODE REVIEW

**Comment by ahuggins** [comment]
screen shot 2018-05-09 at 3 48 08 am

**Comment by ahuggins** [comment]
I saw this uses Bootstrap 4.0.0, so I thought moving the logs and the name of the package to a navbar would be a little nicer. This gives the logs more horizontal width which should make looking at logs a little nicer.

I also added a footer, with links to the Repo and the Issues, cause I know sometimes I have an idea and would like to quickly get to the repo to make an issue or just see the docs. Adding these links makes that easier.

In order to make it look good, I made the Logs a Select box instead of a list. I'm not sure I myself am thrilled with it....but maybe there is a solution we can come up. I had to add a tiny bit of JS to handle the "change() for the select" in order for it to work like navigation for multiple files.

Open to feedback if you want to change something, so let me know.

**Comment by rap2hpoutre** [comment]
Thanks for your contribution, and sorry for late answer!

Some thoughts:

 - I really appreciate the work you have done and I feel it looks better with your changes! 👍 
 - Two "by rap2h" is too much! I think we should just keep one! ;) The one in the bottom of the page seems more appropriate.
 - About the bottom of the page, I think it's a good idea to add "github" and "issues" in the footer! Good job! 👏 
 - The only thing I don't like is the file selector on the top of page. I feel like it introduce some problems:
   - You can not see the whole list of logs, so you have no idea before clicking about the log list length (and content)
   - You don't see it at first glance. If you have a large screen, you could miss it.
   - When you want to check logs one by one (open one, check, open another one, check, etc.), you have two click for each step. I feel like it's a regression.

Anyway, thank you so much. Don't give, up, feel free to answer!

**Comment by ahuggins** [comment]
Cool! No problem on timing, that's how open source goes.

Yeah, the dropdown log file selector felt a little weird to me too. I'll take a look and see if I can figure out a way that works with just links. Thanks for the feedback, I'll try to get something back in a couple days.

**Pull request closed without merging**
