### PR TITLE
Break on all characters instead of words

### PR DESCRIPTION
**Pull request by meijdenmedia**
When breaking on words my layout is acting strange. Breaking on all characters fixes this issue.

log-viewer-break-words

### CODE REVIEW

**Comment by meijdenmedia** [comment]
Hmm I see what you mean, that’s pretty ugly. Will try to find a better solution soon. Do you have any ideas/suggestions?
 
I’m using eyewitness to monitor my Laravel applicatio, they created that file.

**Comment by rap2hpoutre** [comment]
Is it a filename like this: `logs/eyewitness_cron_xxxxxxxxxxxx.cron.log`?

If so maybe we could open a PR on Eyewitness to change this line https://github.com/eyewitness/eye/blob/56eeebc5259ddb9d273c9db279714125edae3920/app/Scheduling/Event.php#L157:

```
$this->output = storage_path('logs/eyewitness_cron_'.sha1($this->mutexName()).'.cron.log');
```

To: 
```
$this->output = storage_path('logs/eyewitness-cron-.sha1($this->mutexName()).'.cron.log');
```

What do you think?

**Comment by rap2hpoutre** [comment]
@meijdenmedia Any news?

**Comment by rap2hpoutre** [comment]
(I just opened an issue)

**Comment by rap2hpoutre** [comment]
@meijdenmedia Fixed via https://github.com/eyewitness/eye/pull/41 Hope it will fix your problem. Just update eyewitness!

**Pull request closed without merging**
