### PR TITLE
Removed paging from logging

### PR DESCRIPTION
**Pull request by osugregor**
Not sure that pagination is really needed for this log viewer? 
Though I would suggest removing it. There is no real performance gain since it is client side anyways.

### CODE REVIEW

**Comment by rap2hpoutre** [comment]
Thank you :).
I don't know what to think about this request. Why should we remove the pagination ? It's not better without: it **seems** less messy with it IMO. I think (not sure) people may not understand why we removed it. 

So, the pagination is not needed (as you said, I agree) and there is no performance gain. But what will be the benefice if we remove this pager for everybody ? I don't know. What is your opinion ? Should we really remove it ?

Regards, 
raph

**Comment by rap2hpoutre** [comment]
Not a solution, but a note: 
In v0.2.3, it now uses local storage to save entry count per page (you can have a look at #22 ). So you can set entry to 100 to show more elements per page.

**Comment by rap2hpoutre** [comment]
@osugregor Without answer, I will close this PR, OK for you ?

**Comment by osugregor** [comment]
Thats fine, its just faster to scroll and navigate/search on a single page.
I commonly use control-f and assumed others do as well. 

It really just comes down to user preference. I wont be hurt if its not integrated.

**Pull request closed without merging**
