### PR TITLE
support for laravel daily logs

### PR DESCRIPTION
**Pull request by djunehor**
In response to issue #202 where the package doesn't detect other log files deep in the year and month folders. I modified the package to generate an array of the directory structure with the files therein so user can click on any file to view logs.
Capture

### CODE REVIEW

**Comment by rap2hpoutre** [comment]
Hi @djunehor, thank you for your contribution! This would be a great enhancement of the log viewer indeed, thank you for your effort! 🎉 I will try to review it next week and merge it if everything is ok!

**Comment by EvilTwin01** [comment]
any update on this its been more that a week?

**Comment by juanpscotto** [comment]
Any news? I'm also waiting for this

**Comment by breaktag** [comment]
Any news? I am waiting on this too?

**Comment by djunehor** [comment]
@rap2hpoutre I've resolved the conflict. Kindly review and merge

**Comment by breaktag** [comment]
@rap2hpoutre Please can you merge this? 
Thank you :)

**Comment by starofsky** [comment]
@rap2hpoutre Please merge this PR and release new version. Thank you so much.

**Comment by moufakkir-zohair** [comment]
@rap2hpoutre Please can you merge this?
Thank you :)

**Comment by 1YalcinSahin1** [comment]
@rap2hpoutre Please can you merge this?
Thank you :)

**Comment by rap2hpoutre** [comment]
@djunehor @EvilTwin01 @juanpscotto @breaktag @starofsky @moufakkir-zohair @1YalcinSahin1 
Thank you for your patience and sorry for the late answer. I just released a new version (2.0.0) that contains this change.

@djunehor Thank you so much for your contribution!

**Comment by 1YalcinSahin1** [comment]
Thank you @rap2hpoutre  but it didn't work properly for me @djunehor 

It writing the whole path instead of the filename.

**Comment by codisfy** [comment]
It also broke the nice glob pattern matching, with matching the expression by splitting pattern like `explode('.', $pattern)[1]`

**Pull request merged**
