### PR TITLE
Log Location customisable #139

### PR DESCRIPTION
**Pull request by elminson**
Ref #139

### CODE REVIEW

**Comment by mikemand** [comment]
The only problem with this is what if someone is storing their logs outside of the `storage` directory entirely? The `storage_path()` helper gives you a path like: `/home/forge/domain.com/storage`.

I would suggest setting the `$this->storage_path` to something like this:

```php
$this->storage_path = function_exists('config') ? config('logviewer.storage_path', 'logs') : storage_path('logs');
```

And then only use `$this->storage_path`, not `storage_path($this->storage_path)` in the code.

**Comment by elminson** [comment]
Sounds perfect! Really good catch! Thanks

**Comment by elminson** [comment]
What about create some test cases on unit test?

**Comment by elminson** [comment]
@rap2hpoutre check the code and let me know if need some adjustment! 
Thanks

**Comment by mikemand** [comment]
@elminson I missed a spot! I'm sorry!

should be:
```diff
- $this->storage_path = function_exists('config') ? config('logviewer.storage_path', 'logs') : storage_path('logs');
+ $this->storage_path = function_exists('config') ? config('logviewer.storage_path', storage_path('logs')) : storage_path('logs');
```

**Comment by mikemand** [comment]
Unit tests would be a great idea, that way it can't be broken somewhere down the line.

**Comment by rap2hpoutre** [comment]
@elminson Thank you! You could have done the last fix (https://github.com/rap2hpoutre/laravel-log-viewer/pull/159/commits/7c4069f4e3a4dc27f313dcddfc40357512497f54 and https://github.com/rap2hpoutre/laravel-log-viewer/pull/159/commits/b592805cfecf66e2a03c0ea13d02e61441853e28) in another PR but it's OK, we need to fix the package which is broken :) so I will merge the whole PR (Log Location customization + fix on #156). It's a bit late (in France) and I have to go to bed because I have a train early in the morning so I have to merge the fix now. Maybe we will do some refactoring after that (I can do it myself). Anyway, thank you for your wok on various subjects today :)

@mikemand Thank you for your help and your review! About unit tests, this lib is a shame: no test, and I not sure where to start: it's really highly coupled to the framework and a specific context. I started some refactoring some days ago (yesterday maybe), it's a required step before testing. One day, there will be tests in this lib and we will be proud of it, not today thought.

@elminson @mikemand  Thanks to both of you!

**Comment by mikemand** [comment]
@rap2hpoutre Yeah, I'm not sure where to even start testing this either. [Orchestral's Testbench](https://github.com/orchestral/testbench) might help, since they allow you to tap even deeper into mocking/stubbing things in the framework.

I know that [Nicolas Widart](https://github.com/nWidart) uses it to test [nWidart/laravel-modules](https://github.com/nWidart/laravel-modules), and there are a lot of filesystem interactions with his modules package.

**Comment by rap2hpoutre** [comment]
@elminson FYI, two small parts were broken, I fixed it in https://github.com/rap2hpoutre/laravel-log-viewer/commit/364cd46e977ed2f894c47842ea3470bc183a3173 (because `0 == null` with loose comparison but `0 !== null`, so it crashed when trying to access `getPattern('something', 0)` with `Array to string conversion`) and https://github.com/rap2hpoutre/laravel-log-viewer/commit/3790892b2b912e7ebaf9ce9868bbe93d542309c7 (because `storage_path() . '/'.$this->storage_path` is like `storage_path() . storage_path()` which is a invalid path). 

Thank you again!

**Comment by elminson** [comment]
Perfect!  @rap2hpoutre  Teamwork!

**Pull request merged**
