### PR TITLE
Support Directory

### PR DESCRIPTION
**Pull request by wangkaibo**
It dosen't work if the Logs directory has one or more directory now.

### CODE REVIEW

**Comment by rap2hpoutre** [comment]
Ok thanks!
I'm curious: How can you have directory in logs directory? Is there a way to do this with Laravel?

**Comment by wangkaibo** [comment]
We use the monolog to record the important operation logs and save in the laravel logs directory.
```php
namespace Loopeer\QuickCms\Services\Utils;

use Monolog\Handler\FirePHPHandler;
use Monolog\Handler\StreamHandler;
use Monolog\Logger;

class LogUtil {

    /**
     * Get log object
     * @param $name
     * @param $dir
     * @return Logger
     */
    public static function getLogger($name, $dir = null) {
        $logger = new Logger($name);
        $date = date('Ymd', time());
        $file_name = $name . '_' . $date . '.log';
        $path = storage_path() . '/logs/' . ($dir ? ($dir . '/') : '') . $file_name;
        $stream = new StreamHandler($path, Logger::INFO);
        $fire_php = new FirePHPHandler();
        $logger->pushHandler($stream);
        $logger->pushHandler($fire_php);
        return $logger;
    }
}
```

**Comment by keneasson** [comment]
This works perfectly for me with Monolog!

**Comment by keneasson** [comment]
I fixed my issue above with the following change:

`	public static function pathToLogFile($file) {
		$logsPath = storage_path('logs');
		if (File::exists($file)) { // try the absolute path
			return $file;
		}

		$file = $logsPath . '/' . $file;

		// check if requested file is really in the logs directory
-		if (dirname($file) !== $logsPath) {
+		if (strpos(dirname($file), $logsPath)) {
			throw new \Exception('No such log file');
		}

		return $file;
	}`

**Comment by melihovv** [comment]
+1 for such functionality!

**Comment by melihovv** [comment]
In my [fork](https://github.com/melihovv/laravel-log-viewer) I implemented such functionality.

**Comment by rap2hpoutre** [comment]
Ok thanks @melihovv! 

Sorry for the late answer. So you should use this "fork" instead if you need directory support (not really a fork though, more like a copy/paste with modifications). This branch has conflict, I close the PR, sorry about that. Let me know if I have done something wrong, I would be happy to have your thought.

**Pull request closed without merging**
