### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mikemand**
Document the change in controller namespace.

### CODE REVIEW

**Comment by mikemand** [comment]
I'd say this fixes #230 and #231, but it is still a breaking change in a minor release so I have a feeling there are going to be a lot of issues opened if those are both closed.

**Comment by rap2hpoutre** [comment]
Thank you so much for your help! I will revert commit, submit a 1.5.1 then release a 2.0 then merge your commit. It's not a good solution but I guess it's not that bad to preserve non-breaking change in minor version (let's say 1.5.1 fixes a regression in 1.5.0).

**Comment by mikemand** [comment]
@rap2hpoutre For v2, you should probably use PSR-4 for loading rather than PSR-0. You'd have to flatten the directory structure a little bit (instead of having a `src/Rap2hpoutre/LaravelLogViewer` directory, things are right in the `src` directory), but it's easier to follow than PSR-0 in my opinion.

**Comment by rap2hpoutre** [comment]
Not sure it's still relevant. Let's close it temporarily. @mikemand Let me know if it's an issue.

**Pull request closed without merging**
