### PR TITLE
Remove facade dependency

### PR DESCRIPTION
**Pull request by Agontuk**
This changes will remove facade dependency from the package as some people want to keep facades disabled in lumen :)

### CODE REVIEW

**Comment by rap2hpoutre** [comment]
Thanks! 
Does it work for both Laravel 4.2, 5.x and Lumen ? I want to keep this package compatible with all versions. Can you just check at least 4.2 and 5.3?

Great work anyway! :)

**Comment by Agontuk** [comment]
Don't know about 4.2, but I'm positive it works on laravel & lumen 5 versions. Okay, I'll check in 4.2

**Comment by Agontuk** [comment]
Last commit makes it compatible with 4.2. response helper method was not available in 4.2, so I used the facade for 4.2 only

**Comment by rap2hpoutre** [comment]
Thank you 👏! Merged!

**Comment by Agontuk** [comment]
anytime :)

**Pull request merged**
