### PR TITLE
Add Description for Config Option 

### PR DESCRIPTION
**Pull request by mg-freelancer**
This PR is related to this issue https://github.com/rap2hpoutre/laravel-log-viewer/issues/125

### CODE REVIEW

**Comment by rap2hpoutre** [comment]
Ok thank you! It just need one more step and I will merge it!

You wrote:

```php
<?php
/*
    |--------------------------------------------------------------------------
    | Log Viewer Pattern
    |--------------------------------------------------------------------------
    |
    | This value is for specify the log viewer pattern.
    |
    */

return [
    'pattern' => env('LOGVIEWER_PATTERN', '*.log'),
];
```
It's not at the right place: your comment is about `pattern` not the `return` statement. Also, the opening comment signs `/*` is not indented. So you could fix by doing this:

```php
<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Log Viewer Pattern
    |--------------------------------------------------------------------------
    |
    | This value is for specify the log viewer pattern.
    |
    */
    'pattern' => env('LOGVIEWER_PATTERN', '*.log'),
];
``` 
Also, you could consider be more descriptive in the comment: why it does exists and what you could do with it (and explaining the default behavior). Random example from Laravel:

```php
    /*
    |--------------------------------------------------------------------------
    | SMTP Host Address
    |--------------------------------------------------------------------------
    |
    | Here you may provide the host address of the SMTP server used by your
    | applications. A default option is provided that is compatible with
    | the Mailgun mail service which will provide reliable deliveries.
    |
    */
```

Anyway, thank you! Feel free to ask me anything!

**Comment by rap2hpoutre** [comment]
@mg-freelancer Any news?

**Comment by rap2hpoutre** [comment]
@mg-freelancer Still there?

**Comment by mg-freelancer** [comment]
I'm sorry I can't read your comments at pervious days, I will do it now

**Comment by elminson** [comment]
@rap2hpoutre Can I do this? This friend forgot this 2 month ago :)

**Comment by rap2hpoutre** [comment]
@elminson Yes feel free to send a PR! Thank you!

**Pull request closed without merging**
