### PR TITLE
Adding Test Class and phpunit + some basic test cases to begin with

### PR DESCRIPTION
**Pull request by elminson**

### CODE REVIEW

**Comment by elminson** [comment]
@rap2hpoutre Please check this first commit for PHPUnit, we can work to put more test cases, in that way we can create new features or fix bugs without breaking what is working.

I use https://github.com/orchestral/testbench to emulate the laravel/framework without installing. I'm open to change any suggestions 

Thanks

**Comment by rap2hpoutre** [comment]
WOW! That's a big move! 

I'm sorry I have not so much time currently (job is hard!) to review and merge your PRs, be sure I really appreciate your contributions! This one is so cool, I thought this lib would have no test ever! I have blocked some time in the next week to review and merge your PRs!

**Comment by elminson** [comment]
@rap2hpoutre thanks for your comments :) I also add tests/laravel.log file to be used for test cases, not sure if we can create dynamic folders (for multi-locations logs files) and delete after the test cases run (in the teardown).

I'm really happy to see all the improvements that we can do together.

**Comment by rap2hpoutre** [comment]
Thank you so much!! Available in v0.22.0 

https://travis-ci.org/rap2hpoutre/laravel-log-viewer/jobs/425032068

**Pull request merged**
